import StarParticles from "@/components/StarParticles";
import "./globals.css";
import { NavbarSimple } from "@/components/Navbar";

export const metadata = {
  title: "Meriç | Portfolio",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StarParticles />
        <NavbarSimple/>
        <main className="font-montserrat mx-auto max-w-screen-2xl">{children}</main>
      </body>
    </html>
  );
}
