import StarParticles from "@/components/StarParticles";
import "./globals.css";
import { NavbarWithMegaMenu } from "@/components/Navbar";


export const metadata = {
  title: "Meriç | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StarParticles />
        <NavbarWithMegaMenu />
        <main>{children}</main>
      </body>
    </html>
  );
}
